### ISSUE TITLE
[Request] Create all necessary files to resume the training for each checkpoint instead of doing it at the end.

### ISSUE THREAD

**Issue by ZeroCool940711** [itsuncheng/fine-tuning-GPT2#1]
Hi there, I recently found this repository and your post explaining how everything works and I have to say its pretty good but on your [post](https://mc.ai/fine-tuning-gpt2-for-text-generation-using-pytorch/) you mention that we can continue training from the last checkpoint but it only works if first you run it until it reaches the first training epoch or if it finishes processing everything. I tried running the code on a huge dataset with billions of parameters and I could not stop it and resume it because it would take too long before it reached the first training epoch, once I stopped it I couldn't resume it as there were some files that were not created by the `run_language_modeling.py` script, I also tested the code with a smaller dataset and there I was able to resume it as the `tokenizer_config.json`, `vocab.json` and other files needed to resume the training were created after it ended. I think it would be a lot more useful if all those files needed to resume the training were created into each checkpoint folder, I know it will probably make the checkpoint use more space but that's should not be a problem as it won't be that much of extra space we will be using.

**Comment by itsuncheng** [comment]
Hey there, thanks for the question! 

I think normally you do have to reach at least the first training epoch to decide the vocabulary of the entire dataset you are using. Is there any reason you cannot reach the first training epoch? FYI you can use tmux, or other similar programs, that will allow you to run a script as a background service. This way, the script will still run while you are disconnected from the remote machine.

**Comment by ZeroCool940711** [comment]
I dont have a problem with leaving it running for a long period of time as its running on a server on my house and not on my computer but the problem is that I tend to run multiple stuff there and train multiple models, sometimes I have to stop the training and continue it later from where it was left, with big datasets I can not do this with your code, for example, i was trying to train it with all the books from the Gutenberg Project which has a lot of books/text that can be used for training and if I had to wait for it to reach the first training epoch it would take me a lot of time, I usually dont train it that much as I can just run it until it reaches a few checkpoints and then it will just be able to generate some text that is good enough, what I do is I first test it to see if the dataset im using is good or if there is something I might have missed and then I continue training if everything is okay but as I said I cant stop your code to do the testing until it reaches the first training epoch. I hope you understand what I meant.

**Comment by itsuncheng** [comment]
I understood your question but unfortunately I don't have an answer now to that. Perhaps you can open the issue on the @huggingface repository!
